<?
$PERM["video"]["*"]="R";
$PERM["certificates"]["8"]="X";
$PERM["kontent-elementa"]["8"]="W";
$PERM["about"]["8"]="X";
$PERM["oplata"]["8"]="X";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>