<?php
namespace D7;

if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();

class DeliveryClass extends \CBitrixComponent implements \Bitrix\Main\Engine\Contract\Controllerable
{
    public function configureActions(): array
    {
        return [
            'ajaxRequest' => [
                'prefilters' => [

                ],
            ],
        ];
    }

    public function onPrepareComponentParams($arParams)
    {

        return $arParams; // TODO: Change the autogenerated stub
    }

    public function executeComponent()
    {
        return parent::executeComponent();
    }

    public function ajaxRequestAction($iblock_id, $product_id)
    {
        if(\CModule::IncludeModule('iblock')){



            ob_start();

            $this->arParams["IBLOCK_ID"]=$iblock_id;
            $i = 0;
			$this->arResult['PRODUCT'] = \CCatalogProduct::GetByID($product_id);

            $arSelect = Array("ID", "IBLOCK_ID", "NAME", "CODE", "PREVIEW_TEXT", "DETAIL_TEXT", "PROPERTY_*");
            $arFilter = Array("IBLOCK_ID"=>$this->arParams["IBLOCK_ID"], "ACTIVE"=>"Y", "PROPERTY_SITES"=>Array($_SERVER['HTTP_HOST'], "*"));


            if ($_REQUEST["ID"]) $arFilter['ID'] = $_REQUEST["ID"];

            $res = \CIBlockElement::GetList(Array("SORT"=>"ASC", "ID"=>"ASC"), $arFilter, false, Array(), $arSelect);
            while($ob = $res->GetNextElement())
            {
                $this->arResult["ITEMS"][$i] = $ob->GetFields();
                $this->arResult["ITEMS"][$i]['PROP'] = $ob->GetProperties();
                $i++;
            }


        }


            $this->IncludeComponentTemplate('ajax_lite', '/local/components/d7/delivery/templates/krep-komp');

            return ob_get_clean();
    }

}